services:
  rd-rs:
    image: ghcr.io/darkseidam/rd-rs:latest
    container_name: rd-rs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./config.toml:/app/config.toml:ro
      - rd-cache:/cache/zurg-vfs
      - type: bind
        source: /mnt/test
        target: /mnt/test
        bind:
          propagation: rshared
    restart: unless-stopped

volumes:
  rd-cache:
